name: Bug report
description: Report a reproducible problem.
title: "[Bug] "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: A short description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide clear reproduction steps.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      description: Device, iOS version, Xcode version, and branch/commit.
      placeholder: iPhone 15 / iOS 18.x / Xcode 17.x / commit abc1234
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Add relevant logs. Redact secrets before posting.
